version: '3.3'

services:
    nginx:
        build:
           context: .
           dockerfile: web.docker
        volumes:
           - ./:/var/www
        ports:
           - 8098:80
        links:
           - fpm

    fpm:
        build:
            context: .
            dockerfile: fpm.docker
        volumes:
           - ./:/var/www//Laravel
        links:
           - db

    db:
        image: mysql:5.7
        environment:
              - MYSQL_DATABASE=laravel
              - MYSQL_ROOT_PASSWORD=root
        ports:
          - 33061:3306
